### ISSUE TITLE
WindowsでZIPタスクがエラーでる件

### ISSUE THREAD

**Issue by TsubasaHiga** [TsubasaHiga/Quicint#70]
エラーの内容。
``` bash
[00:37:59] Finished 'jsBuild' after 8.99 s
[00:37:59] Starting 'genZipArchive'...
[00:37:59] 'genZipArchive' errored after 4.56 ms
[00:37:59] TypeError: dt.toFormat is not a function
    at genZipArchive (c:\Users\HigaTsubasa\Desktop\test\node_modules\quicint\gulpfile.js:358:19)
    at bound (domain.js:419:14)
    at runBound (domain.js:432:12)
    at asyncRunner (c:\Users\HigaTsubasa\Desktop\test\node_modules\quicint\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

gulpfile.jsのこの辺。
``` javascript
const dt = new Date()
const date = dt.toFormat('YYMMDD-HHMI')
```

**Comment by TsubasaHiga** [comment]
```
const dateutils = require('date-utils')
```
の読み込みまで消してしまっていたのがミスでしたので戻し。
